# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to GHCR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 8.0/edge
  workflow_dispatch:
    inputs:
      risk:
        description: Releases this rock to desired risk
        required: true
        type: choice
        options:
          - edge
          - beta
          - candidate
          - stable

jobs:
  build:
    name: Build rock
    uses: canonical/data-platform-workflows/.github/workflows/build_rock.yaml@v50
    permissions:
      contents: read

  release:
    name: Release rock
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_rock_edge.yaml@v50
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    permissions:
      packages: write  # Needed to publish to GitHub Container Registry
      contents: write  # Needed to create git tags

  sbom:
    name: Generate Software Bill of Materials
    needs:
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {}
    steps:
      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Download rock package(s)
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*
          merge-multiple: true
      - name: Generate SBOM(s)
        shell: python
        run: |
          import pathlib
          import subprocess

          for rock_file in pathlib.Path(".").glob("*.rock"):
              subprocess.run(
                  ["syft", rock_file.name, "--output", f"spdx-json={rock_file.name}.spdx.json"],
                  check=True,
              )
      - name: Upload SBOM(s)
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ needs.build.outputs.artifact-prefix }}
          path: '*.spdx.json'
          if-no-files-found: error

  oci-factory:
    name: Update OCI-Factory
    needs:
      - release
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Golang setup
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.0"
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install git
          sudo apt install yq
          go install github.com/canonical/oci-factory/tools/cli-client/cmd/oci-factory@latest
      - name: Set binary paths to environment
        run: |
          echo OCI_FACTORY="$(go env GOPATH)/bin/oci-factory" >> "${GITHUB_ENV}"
      - name: Set release risk to environment
        run: |
          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
            echo TARGET_RISK=${{ inputs.risk }} >> "${GITHUB_ENV}"
          else
            echo TARGET_RISK=edge >> "${GITHUB_ENV}"
          fi
      - name: Set image version to environment
        run: |
          {
            echo END_OF_LIFE="$(date -d '+ 5 years' '+%Y-%m-%d')"
            echo MYSQL_MAJOR_VERSION="$(yq --raw-output '.version | split(".")[0]' rockcraft.yaml)"
            echo MYSQL_MINOR_VERSION="$(yq --raw-output '.version | split(".")[1]' rockcraft.yaml)"
            echo OS_VERSION="$(yq --raw-output '.base | split("@")[1]' rockcraft.yaml)"
          } >> "${GITHUB_ENV}"
      - name: Release
        run: |
          "${OCI_FACTORY}" upload -y --release \
            track="${MYSQL_MAJOR_VERSION}.${MYSQL_MINOR_VERSION}-${OS_VERSION},eol=${END_OF_LIFE},risks=${TARGET_RISK}"
        env:
          GITHUB_TOKEN: ${{ secrets.DP_BOT_PAT }}
